### ISSUE TITLE
前台页面html的编写

### ISSUE THREAD

**Issue by ChaoHui123** [CNMAKER/ChatRobot#1]
@1179734190 @jiamengwei 

前台页面的编写主要模仿 [微信网页版](https://wx.qq.com/) 的ui ,聊天窗口的工具栏 暂时不做(表情,截图,发送文件)
![tim 20170502180820](https://cloud.githubusercontent.com/assets/17821872/25613930/90cfd964-2f62-11e7-86e7-24459e0b4360.jpg)
![tim 20170502181233](https://cloud.githubusercontent.com/assets/17821872/25614025/e29bc0dc-2f62-11e7-9773-bd800f02faf1.jpg)

**Comment by 1179734190** [comment]
@ChaoHui123 现在做到哪了？

**Comment by 1179734190** [comment]
@ChaoHui123 微信网页版有注册按钮？

**Comment by ChaoHui123** [comment]
> 现在做到哪了？

就做个了个登录界面

**Comment by ChaoHui123** [comment]
合并完了 你们同步下代码 @1179734190 @jiamengwei
